FROM node:latest AS build
WORKDIR /build

COPY package.json package.json
COPY package-lock.json package-lock.json
RUN npm install

COPY public/ public
COPY src/ src
COPY assets/ assets
CMD npm start

